"""Update table names for all models

Revision ID: 09608b749c1a
Revises: 
Create Date: 2025-09-28 02:58:47.094535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09608b749c1a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_code')
    )
    op.create_index(op.f('ix_course_details_id'), 'course_details', ['id'], unique=False)
    op.create_table('prof_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prof_details_id'), 'prof_details', ['id'], unique=False)
    op.create_table('student_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id_str', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_details_id'), 'student_details', ['id'], unique=False)
    op.create_index(op.f('ix_student_details_student_id_str'), 'student_details', ['student_id_str'], unique=True)
    op.create_table('enrollment_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('quiz_score_1', sa.Float(), nullable=True),
    sa.Column('quiz_score_2', sa.Float(), nullable=True),
    sa.Column('quiz_score_3', sa.Float(), nullable=True),
    sa.Column('assignment_1', sa.Float(), nullable=True),
    sa.Column('assignment_2', sa.Float(), nullable=True),
    sa.Column('assignment_3', sa.Float(), nullable=True),
    sa.Column('attendance', sa.Float(), nullable=True),
    sa.Column('mid_term_1_score', sa.Float(), nullable=True),
    sa.Column('average_overall_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course_details.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollment_details_id'), 'enrollment_details', ['id'], unique=False)
    op.create_table('professor_courses',
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course_details.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['prof_details.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professor_courses')
    op.drop_index(op.f('ix_enrollment_details_id'), table_name='enrollment_details')
    op.drop_table('enrollment_details')
    op.drop_index(op.f('ix_student_details_student_id_str'), table_name='student_details')
    op.drop_index(op.f('ix_student_details_id'), table_name='student_details')
    op.drop_table('student_details')
    op.drop_index(op.f('ix_prof_details_id'), table_name='prof_details')
    op.drop_table('prof_details')
    op.drop_index(op.f('ix_course_details_id'), table_name='course_details')
    op.drop_table('course_details')
    # ### end Alembic commands ###
